layer_id: "BlueMarble"
layer_title: "Blue Marble (MODIS)"
layer_name: "BlueMarble tileset"
projection: "EPSG:4326"
tilematrixset: "500m"
mime_type: "image/jpeg"
static: true
abstract: "BlueMarble abstract"
metadata:
  - {}
source_mrf:
  size_x: 81920
  size_y: 40960
  bands: 3
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/profiler/BlueMarble/BlueMarble.idx"
  data_file_uri: "{S3_URL}/profiler/BlueMarble.pjg"
  year_dir: false
  bbox: -180,-90,180,90
  empty_tile: "/etc/onearth/empty_tiles/Blank_RGB_512.jpg"